use crate::state::ResourceInstance;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};

// ── public entry point ───────────────────────────────────────────────────────

/// Generate a complete, plan/apply-ready HCL file from state resources.
///
/// Output sections (in order):
///   1. File header comment
///   2. `terraform { required_providers { … } }` block
///   3. `provider "<name>" { … }` skeleton blocks (one per unique provider)
///   4. `import { … }` blocks (Terraform ≥ 1.5, managed resources only)
///   5. `resource` / `data` blocks with computed & sensitive attrs handled
pub fn generate_hcl(resources: &[ResourceInstance]) -> String {
    let mut out = String::new();

    out.push_str("# Generated by terraform-settings-mapper\n");
    out.push_str("# Do not edit manually – re-run the tool to refresh.\n");
    out.push_str("#\n");
    out.push_str("# Requires Terraform >= 1.5 (import blocks).\n");
    out.push_str("# Fill in provider configuration before running terraform init.\n\n");

    render_terraform_block(&mut out, resources);
    render_provider_blocks(&mut out, resources);
    render_import_blocks(&mut out, resources);
    render_resource_blocks(&mut out, resources);

    out
}

// ── section renderers ────────────────────────────────────────────────────────

fn render_terraform_block(out: &mut String, resources: &[ResourceInstance]) {
    // Collect unique provider sources, sorted for determinism.
    let sources: BTreeSet<(&str, &str)> = resources
        .iter()
        .map(|r| (r.provider_local_name.as_str(), r.provider_source.as_str()))
        .collect();

    out.push_str("terraform {\n");
    out.push_str("  required_providers {\n");
    for (local_name, source) in &sources {
        out.push_str(&format!("    {local_name} = {{\n"));
        out.push_str(&format!("      source = \"{source}\"\n"));
        out.push_str("    }\n");
    }
    out.push_str("  }\n");
    out.push_str("}\n\n");
}

fn render_provider_blocks(out: &mut String, resources: &[ResourceInstance]) {
    // One skeleton provider block per unique local name.
    let mut seen: BTreeMap<&str, &str> = BTreeMap::new();
    for r in resources {
        seen.entry(&r.provider_local_name).or_insert(&r.provider_source);
    }

    for (local_name, _source) in &seen {
        out.push_str(&format!("provider \"{local_name}\" {{\n"));
        out.push_str("  # Configure authentication and region as needed.\n");
        out.push_str("  # See provider documentation for available arguments.\n");
        out.push_str("}\n\n");
    }
}

fn render_import_blocks(out: &mut String, resources: &[ResourceInstance]) {
    let managed: Vec<&ResourceInstance> = resources
        .iter()
        .filter(|r| r.mode == "managed")
        .collect();

    if managed.is_empty() {
        return;
    }

    out.push_str("# ── Import blocks (tie existing infrastructure to this config) ──────────────\n");
    for res in &managed {
        let id = match &res.resource_id {
            Some(id) => id.clone(),
            None => {
                out.push_str(&format!(
                    "# import {{ to = {}  id = \"TODO\" }}\n",
                    res.address()
                ));
                continue;
            }
        };
        out.push_str("import {\n");
        out.push_str(&format!("  to = {}\n", res.address()));
        out.push_str(&format!("  id = \"{}\"\n", escape_hcl_string(&id)));
        out.push_str("}\n\n");
    }
}

fn render_resource_blocks(out: &mut String, resources: &[ResourceInstance]) {
    out.push_str("# ── Resource / data blocks ───────────────────────────────────────────────────\n");
    for res in resources {
        match res.mode.as_str() {
            "managed" => render_managed(out, res),
            "data" => render_data(out, res),
            other => {
                out.push_str(&format!("# Skipped unknown mode '{other}': {}\n", res.address()));
            }
        }
        out.push('\n');
    }
}

// ── individual block renderers ───────────────────────────────────────────────

fn render_managed(out: &mut String, res: &ResourceInstance) {
    if res.module_path.is_some() {
        out.push_str(&format!("# module address: {}\n", res.address()));
    }
    if let Some(idx) = &res.index {
        out.push_str(&format!("# instance index: {idx}\n"));
    }

    out.push_str(&format!(
        "resource \"{}\" \"{}\" {{\n",
        res.resource_type, res.name
    ));

    if let Value::Object(map) = &res.attributes {
        for (k, v) in map {
            // `id` is always computed — never set it in config
            if k == "id" {
                continue;
            }
            render_attribute(out, k, v, 1, &res.sensitive_top_keys);
        }
    }

    out.push_str("}\n");
}

fn render_data(out: &mut String, res: &ResourceInstance) {
    if res.module_path.is_some() {
        out.push_str(&format!("# module address: {}\n", res.address()));
    }

    out.push_str(&format!(
        "data \"{}\" \"{}\" {{\n",
        res.resource_type, res.name
    ));

    if let Value::Object(map) = &res.attributes {
        for (k, v) in map {
            if k == "id" {
                continue;
            }
            render_attribute(out, k, v, 1, &res.sensitive_top_keys);
        }
    }

    out.push_str("}\n");
}

// ── attribute rendering ──────────────────────────────────────────────────────

fn render_attribute(
    out: &mut String,
    key: &str,
    value: &Value,
    depth: usize,
    sensitive_keys: &std::collections::HashSet<String>,
) {
    let indent = "  ".repeat(depth);

    // Sensitive top-level attributes: emit null with a comment so the file is
    // valid HCL that can be planned (provider will prompt / error with guidance).
    if depth == 1 && sensitive_keys.contains(key) {
        out.push_str(&format!(
            "{indent}{key} = null # sensitive – set via variable or environment\n"
        ));
        return;
    }

    match value {
        Value::Null => {
            // Omit null values – they were not set in state
        }
        Value::Bool(b) => {
            out.push_str(&format!("{indent}{key} = {b}\n"));
        }
        Value::Number(n) => {
            out.push_str(&format!("{indent}{key} = {n}\n"));
        }
        Value::String(s) => {
            if s.contains('\n') {
                out.push_str(&format!("{indent}{key} = <<-EOT\n{s}\nEOT\n"));
            } else {
                out.push_str(&format!(
                    "{indent}{key} = \"{}\"\n",
                    escape_hcl_string(s)
                ));
            }
        }
        Value::Array(arr) => {
            if arr.is_empty() {
                out.push_str(&format!("{indent}{key} = []\n"));
            } else if arr.iter().all(is_scalar) {
                let items: Vec<String> = arr.iter().map(scalar_to_hcl).collect();
                out.push_str(&format!("{indent}{key} = [{}]\n", items.join(", ")));
            } else {
                for item in arr {
                    out.push_str(&format!("{indent}{key} {{\n"));
                    if let Value::Object(map) = item {
                        for (k, v) in map {
                            render_attribute(out, k, v, depth + 1, sensitive_keys);
                        }
                    }
                    out.push_str(&format!("{indent}}}\n"));
                }
            }
        }
        Value::Object(map) => {
            if map.is_empty() {
                out.push_str(&format!("{indent}{key} = {{}}\n"));
            } else {
                out.push_str(&format!("{indent}{key} {{\n"));
                for (k, v) in map {
                    render_attribute(out, k, v, depth + 1, sensitive_keys);
                }
                out.push_str(&format!("{indent}}}\n"));
            }
        }
    }
}

// ── helpers ──────────────────────────────────────────────────────────────────

fn is_scalar(v: &Value) -> bool {
    matches!(v, Value::Bool(_) | Value::Number(_) | Value::String(_))
}

fn scalar_to_hcl(v: &Value) -> String {
    match v {
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => format!("\"{}\"", escape_hcl_string(s)),
        _ => "null".to_owned(),
    }
}

fn escape_hcl_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\r', "\\r")
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state;

    const SAMPLE_STATE: &str = r#"{
        "version": 4,
        "terraform_version": "1.6.0",
        "resources": [
            {
                "mode": "managed",
                "type": "aws_vpc",
                "name": "main",
                "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
                "instances": [{
                    "attributes": {
                        "id": "vpc-abc123",
                        "cidr_block": "10.0.0.0/16",
                        "enable_dns_support": true,
                        "tags": {"Name": "main"}
                    },
                    "sensitive_attributes": []
                }]
            },
            {
                "mode": "managed",
                "type": "aws_db_instance",
                "name": "primary",
                "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
                "instances": [{
                    "attributes": {
                        "id": "mydb",
                        "engine": "postgres",
                        "password": "s3cr3t",
                        "username": "admin",
                        "instance_class": "db.t3.micro"
                    },
                    "sensitive_attributes": [["password"]]
                }]
            },
            {
                "mode": "data",
                "type": "aws_ami",
                "name": "ubuntu",
                "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
                "instances": [{
                    "attributes": {
                        "id": "ami-12345",
                        "most_recent": true,
                        "owners": ["099720109477"]
                    },
                    "sensitive_attributes": []
                }]
            }
        ]
    }"#;

    fn get_hcl() -> String {
        let json: serde_json::Value = serde_json::from_str(SAMPLE_STATE).unwrap();
        let resources = state::parse_state(&json).unwrap();
        generate_hcl(&resources)
    }

    #[test]
    fn has_terraform_block() {
        let hcl = get_hcl();
        assert!(hcl.contains("terraform {"), "missing terraform block");
        assert!(hcl.contains("required_providers {"), "missing required_providers");
        assert!(hcl.contains(r#"source = "hashicorp/aws""#), "missing provider source");
    }

    #[test]
    fn has_provider_skeleton() {
        let hcl = get_hcl();
        assert!(hcl.contains(r#"provider "aws" {"#), "missing provider block");
    }

    #[test]
    fn has_import_blocks() {
        let hcl = get_hcl();
        assert!(hcl.contains("import {"), "missing import block");
        assert!(hcl.contains("to = aws_vpc.main"), "missing import to address");
        assert!(hcl.contains(r#"id = "vpc-abc123""#), "missing import id");
    }

    #[test]
    fn id_not_in_resource_body() {
        let hcl = get_hcl();
        // Split at the resource block start and check its body has no `  id =`
        let after_resource = hcl
            .split(r#"resource "aws_vpc" "main" {"#)
            .nth(1)
            .expect("resource block missing");
        let body = after_resource.split('}').next().unwrap_or("");
        assert!(!body.contains("  id ="), "id must not appear in resource body");
    }

    #[test]
    fn sensitive_attr_is_null() {
        let hcl = get_hcl();
        assert!(
            hcl.contains("password = null # sensitive"),
            "sensitive attr must be nulled"
        );
    }

    #[test]
    fn data_source_uses_data_keyword() {
        let hcl = get_hcl();
        assert!(hcl.contains(r#"data "aws_ami" "ubuntu" {"#), "data source must use data keyword");
        assert!(!hcl.contains(r#"resource "aws_ami""#), "data source must not use resource keyword");
    }

    #[test]
    fn no_import_for_data_source() {
        let hcl = get_hcl();
        assert!(!hcl.contains("to = aws_ami.ubuntu"), "data source must not have import block");
    }
}
